---
  - name: web | config_web_server.yml | install nginx
    apt: name={{ nginx.package }}={{ nginx.version }} state=present

  - shell: ls -1 /etc/nginx/sites-available
    register: nginx_sites_available_contents

  - name: web | config_web_server.yml | remove all nginx site configurations in sites-available
    file: path=/etc/nginx/sites-available/{{ item }} state=absent
    with_items: nginx_sites_available_contents.stdout_lines

  - shell: ls -1 /etc/nginx/sites-enabled
    register: nginx_sites_enabled_contents

  - name: web | config_web_server.yml | remove all nginx site configurations in sites-enabled
    file: path=/etc/nginx/sites-enabled/{{ item }} state=absent
    with_items: nginx_sites_enabled_contents.stdout_lines

  - name: web | config_web_server.yml | remove default configuration
    file: path=/etc/nginx/conf.d/default.conf state=absent

  - name: web | config_web_server.yml | ensure nginx configuration
    template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf group=root owner=root

  - name: web | config_web_server.yml | copy nginx vhosts
    template: src=hnlmakerfaire.j2 dest=/etc/nginx/sites-available/hnlmakerfaire

  - name: web | config_web_server.yml | enable vhosts in sites-enabled
    file: src=/etc/nginx/sites-available/hnlmakerfaire path=/etc/nginx/sites-enabled/hnlmakerfaire state=link
