---
  - name: web | config_dependencies.yml | ensure uwsgi dependencies installed
    apt: name={{ item }} update_cache=yes cache_valid_time=3600
    with_items:
      - build-essential
      - python
      - python-dev
      - python-pip
