---
  - name: web | config_application_server.yml | install uwsgi
    pip: name={{ uwsgi.package }} version={{ uwsgi.version }}

  - name: web | config_application_server.yml | ensure uwsgi directories
    file: path={{ item }} state=directory group=root owner=root
    with_items:
      - '/etc/uwsgi/apps-available'
      - '/etc/uwsgi/apps-enabled'

  - name: web | config_application_server.yml | ensure uwsgi configuration
    template: src=hnlmakerfaire.xml.j2 dest=/etc/uwsgi/apps-available/hnlmakerfaire.xml group=root owner=root

  - name: web | config_application_server.yml | enable uwsgi in sites-enabled
    file: src=/etc/uwsgi/apps-available/hnlmakerfaire.xml path=/etc/uwsgi/apps-enabled/hnlmakerfaire.xml state=link
